### ISSUE TITLE
Published story gets "Unexpected Error" when attempt to view from Story Detail Page

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#653] opened 2013-02-25 17:28 UTC
This is the story:
http://floodlightproject.org/en/stories/dreams-ruler-community-needs-your-support-and-help/

I was viewing in Chrome.

**Comment by jwirfs-brock** [comment] 2013-02-25 17:28
Also this story: http://floodlightproject.org/en/stories/united-way-and-mountain-resource-center-train-moms/

These are the two most recently published stories, I believe.

**Comment by ghing** [comment] 2013-02-25 17:33
I've looked into these.  These are both being caused by #534/#535.  I am also working on a work-around so that the users will not see the unexpected error page (though the author may not see the asset they expect in the story). I'll email you the user names of the authors if you want to reach out to the users.  If they want, I can "fix" their stories on the back-end.

I'm going to close this as it's a duplicate of #534/#535.

**Closed as completed by ghing** 2013-02-25 17:33 UTC
Labels: bug

**Comment by jwirfs-brock** [comment] 2013-02-25 17:35
Gotcha -- I figured you might already be working on it.

I'll reach out to those users and let them know we're working on the
problem. I can just get their emails through the admin.

Thanks,
Jordan
