### ISSUE TITLE
Google charts embed code (for interactive version) not rendering in Story Builder

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#281] opened 2012-10-03 16:28 UTC
Jon Denzler has been trying to embed some interactive charts he created using Google Docs. I've been experimenting with the chart he was trying to embed, and have also been having trouble.

Because we don't have a graph/chart asset, I've been trying to insert this as a table.

You can view the chart at: https://docs.google.com/spreadsheet/ccc?key=0AhWnhIC_xoBpdEpNQkRpdGN6V1FJQ1Y4NEVhQU83b1E#gid=2

 Here is the embed code produced via Google Docs:

<script type="text/javascript" src="//ajax.googleapis.com/ajax/static/modules/gviz/1.0/chart.js"> {"dataSourceUrl":"//docs.google.com/spreadsheet/tq?key=0AhWnhIC_xoBpdEpNQkRpdGN6V1FJQ1Y4NEVhQU83b1E&transpose=0&headers=1&range=R12%3AV20&gid=0&pub=1","options":{"vAxes":[{"useFormatFromData":true,"title":"Cost in Dollars","minValue":null,"viewWindowMode":"pretty","viewWindow":{"min":null,"max":null},"gridlines":{"count":"10"},"maxValue":null},{"useFormatFromData":true,"minValue":null,"viewWindowMode":"pretty","viewWindow":{"min":null,"max":null},"maxValue":null}],"booleanRole":"certainty","title":"Cost Per Nutrients","animation":{"duration":0},"legend":"right","hAxis":{"useFormatFromData":true,"title":"\"Food\" Name","slantedTextAngle":30,"slantedText":true,"minValue":null,"viewWindowMode":null,"viewWindow":null,"maxValue":null},"tooltip":{},"isStacked":false,"width":1793,"height":790},"state":{},"view":{},"chartType":"ColumnChart","chartName":"Chart 4"} </script>

And the embed code for the image:
<img src="https://docs.google.com/spreadsheet/oimg?key=0AhWnhIC_xoBpdEpNQkRpdGN6V1FJQ1Y4NEVhQU83b1E&oid=7&zx=tu6n9tp6r8p2" />

Neither the link or the interactive embed code renders in the Story Builder (or the preview), but the embed code for the static image works.

**Comment by ghing** [comment] 2012-10-03 16:37
I'll add a graph/chart asset type today.  

The embedding of charts is a known issue (I think there's already an issue open for it) that I haven't had time to investigate.  I'll let you know what my task queue looks like today and you can tell me where to prioritize this.

**Comment by ghing** [comment] 2012-10-03 16:51
This is a duplicate of #187.  The issue for adding the chart type is #189.  I'm going to close this issue and continue to track it in the original issue.

**Closed as completed by ghing** 2012-10-03 16:51 UTC
Labels: builder, embedding

**Comment by jwirfs-brock** [comment] 2012-10-03 16:53
Ok, sounds good. Sorry for the duplication.
