### ISSUE TITLE
Table of Contents menu not working in modal viewer

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#715] opened 2013-04-16 15:18 UTC
To replicate:
1. Navigate to http://www.floodlightproject.org/en/stories/day-of-service-at-walnut-hill-in-the-childrens-cor/
2. View story.
3. Click on table of contents item in lower right-hand corner.
4. In the table of contents, click on a section.

Expected result: Selected section is displayed

Observed result: nothing happens.

Note that this works correctly when the viewer is displayed in a separate window/tab.

Possibly related error:

> TypeError: $(...).attr(...) is undefined
> http://dev2.floodlightproject.org/static/js/viewer/views.js
> Line 271

**Comment by ghing** [comment] 2013-04-16 15:45
Updated issue title, description to reflect some troubleshooting that we did.

**Comment by ghing** [comment] 2013-04-16 16:03
This is a regression as a result of 81b20c207814703c2eb336a054412a5759612479.

Since the router is no longer used when in the modal window (to fix #487), the view is not updated as a result of visiting the URL of the ToC item links.  The code base was updated to accommodate this change for the next/previous buttons, but not for the ToC items.

**Comment by ghing** [comment] 2013-04-16 16:18
Assigning to @patternleaf  to fix.

**Closed as completed** 2013-05-09 21:44 UTC
Labels: bug, viewer
