### ISSUE TITLE
Tools tips on filters on Explore page obscure the drop-down list

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#320] opened 2012-10-11 19:16 UTC
When you are trying to use one of the filters on Explore, the tool tips opens below. This makes is so that when  you click the filter, you initially don't see the search box, which makes it really easy to miss.

See image: https://docs.google.com/file/d/0B82exFJJWyJqaUFYNXVSSEJRR0U/edit

We could solve this by having the tool tip appear above the filter, instead of below.

**Comment by patternleaf** [comment] 2012-10-14 21:44
i encountered this too (see #301) and tried moving the tooltips above. the issue is then that when the filter bar is in floating mode, there's a lot of space required above the filters to host the tooltips. don't know if that's a deal-breaker, but it's less than ideal.

**Comment by jwirfs-brock** [comment] 2012-10-15 15:14
Oh, I see what you mean. Would it be possible to either:
- increase the space above the sticky filters
- turn the tool tips off when the filters are in sticky mode

If neither of those make sense, it might be ok to just have to tool tip above but cut off during sticky mode. I still think that's better than having it obscure the filters.

**Comment by ghing** [comment] 2013-01-07 13:46
Re-closed by 78fc211, change is live on staging

**Closed as completed by ghing** 2013-01-07 13:46 UTC
Labels: 2 points

**Comment by ghing** [comment] 2013-01-07 13:48
Assigning to @jwirfs-brock for final review.
