### ISSUE TITLE
Error uploading image in new story builder

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#925] opened 2014-01-23 23:29 UTC
Here's the error message I'm getting:

"Oops, couldn't add your asset here. This is probably because you already did so in another tab or window. Hold tight while we refresh this section's assets."

It's in this story: http://floodlightproject.org/en/build/654b9af156794e3caa30edcf5a8789d8/

I only have one Floodlight window open at the moment. I did a save and refresh, and am still getting the error. It looks like the image uploads and then renders for a second before it disappears and I see the message.

The set-up for this was pretty standard. I was, however, working in a place with a spotty wifi connection (it should be good now), so I'm not sure if that has something to do with it.

Here's a screen shot with the error message. If you want to see the image load then disappear, I can get a video screen capture as well.

![screen shot 2014-01-23 at 4 27 32 pm](https://f.cloud.github.com/assets/1020518/1990535/0320798c-8486-11e3-9ac8-05c0514c2b04.png)

I'm currently using Chrome version 32.0.1700.77.

**Comment by jwirfs-brock** [comment] 2014-01-23 23:30
I did another refresh and it looks like the image upload actually worked, I just couldn't see it until the refresh. Weird!

**Comment by ghing** [comment] 2014-01-24 15:22
@jwirfs-brock, were you able to continue authoring your story after the refresh, or do you need me to go in and fix things at the database level? If you aren't stalled, I'll wait until I've finished the responsive stuff to look into this.

**Comment by jwirfs-brock** [comment] 2014-01-24 15:28
@ghing I was able to finish the story. Yes, you should finish up the responsive stuff and then come back to this. Thanks!

**Comment by ghing** [comment] 2014-01-30 17:30
Ok. I just saw this in my local development instance, but then wasn't able to replicate it.  

This seems like an AJAX race condition somewhere in the code.  When I get to a good stopping point, I'll do a code audit and maybe write some unit tests to try to track it down.

Note that after refreshing the browser, I was able to recover from the issue.

**Comment by ghing** [comment] 2014-02-05 16:49
This is just a brain dump of thoughts as I try to replicate or find root causes of this issue:

Here's a list of scenarios that could cause the "Oops, couldn't add your asset here. This is probably because you already did so in another tab or window. Hold tight while we refresh this section's assets." error:
- Builder open in multiple windows/tabs.  This was the assumed cause, but as @jwirfs-brock noted in the issue, this wasn't the case for her.
- Builder sending duplicate section asset requests.  This could be the case, as I saw at least one error on production where the asset being assigned to a section container matches the one already there.
- Request to create a section asset succeeding on the server, but the client never receiving the server's response due to a slow/shaky connection.

Flow for creating a new image asset by uploading an image file:
1. `SectionAssetEditView.processForm()` is called when the form is submitted
2. `SectionAssetEditView.processForm()` calls `SectionAssetEditView.saveModel()`
3. `SectionAssetEditView.saveModel()` sets up a success callback for `Asset.save()` that will trigger a `do:add:sectionasset` event on the event bus and then calls `Asset.save()`.
4. The image is uploaded and the asset model is created on the server.  The success callback to `Asset.save()` triggers the a `do:add:sectionasset` event on the event bus.
5. When the `SectionEditView` for the section where the asset was added was initialized, it adds an event listener for the event bus event `do:add:sectionasset`.  The event handler is `SectionEditView.addAsset()`. 
6. `SectionEditView.addAsset()` adds the the asset to the `SectionEditView.assets` collection, which is a `storybase.models.SectionAssets` collection.
7.  `SectionAssets` has an internal event listener, `SectionAssets.setSectionAsset()`,  for the collection's `add` event
8. `SectionAssets.setSectionAsset()` calls `SectionAssets.updateSectionAsset()`.
9. `SectionAsset.updateSectionAsset()` creates a new `SectionAsset` model and calls its `save()` method.
10. `SectionAssetEditView.saveModel()` changes the view's state to `display` and re-renders.  Note that this happens whether or not the saving of the `SectionAsset` model succeeds or fails.

Note: I noticed that the section asset is created with a PUT request to
/api/0.1/stories/<story_id>/sections/<section_id>/assets/<asset_id>/.

This is a PUT rather than a POST (what I'd expect) because the initializer for the `SectionAsset` model sets the `id` attribute of the model.  I'm pretty sure that the existence of an `id` attribute is used by `Backbone.Model.save()` to determine if the model is new or not and whether a PUT or POST request should be sent.  I'm not sure if this makes a big difference because I think Tastypie will just create a new model for a PUT, if it doesn't already exist.

**Closed as completed** 2016-06-28 19:52 UTC
Labels: bug, builder
