### ISSUE TITLE
Google Fusion Tables embed rendering strangely in Firefox

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#862] opened 2013-09-09 19:42 UTC
I was trying to update the story http://floodlightproject.org/en/stories/dataviz-how-to-make-a-bar-chart-in-fusion-tables/, which has embedded Google Fusion Tables charts on sections 11, 12, 17, and 18.

Here's the link to the story in the builder: http://floodlightproject.org/en/build/6e7fec72fa3143a99b1ee6401e669ca4/

The charts are rendering correctly in Chrome:
![screen shot 2013-09-09 at 1 36 56 pm](https://f.cloud.github.com/assets/1020518/1109807/88d6a624-1987-11e3-9b48-ad45b0b0d401.png)

But in Firefox, they are all appearing smaller than the dimensions specified in the embed code, which causes them to appear funny/garbled:
![screen shot 2013-09-09 at 1 36 11 pm](https://f.cloud.github.com/assets/1020518/1109810/9dd7c2d8-1987-11e3-8a3f-ddf11b81582e.png)

**Comment by ghing** [comment] 2013-09-11 21:14
I was able to replicate this in Firefox 23.0 and also confirm that it doesn't seem to be a problem in Chrome. 

Here's the embed code for one of the Fusion Tables-based graphics that wasn't working right:

```
<iframe width="900" height="600" scrolling="no" frameborder="no" src="https://www.google.com/fusiontables/embedviz?containerId=gviz_canvas&amp;q=select+col0%2C+col1%2C+col2%2C+col3%2C+col4%2C+col5%2C+col6+from+1Kq6RQfNVEco_IcB1kDs4d1owYqIsZ4DG8JbEj48+order+by+col0+asc+limit+10&amp;viz=GVIZ&amp;t=COLUMN&amp;uiversion=2&amp;gco_forceIFrame=true&amp;gco_hasLabelsColumn=true&amp;gco_type=columns&amp;gco_vAxes=%5B%7B%22title%22%3A%22%22%2C+%22minValue%22%3Anull%2C+%22maxValue%22%3Anull%2C+%22useFormatFromData%22%3Atrue%2C+%22viewWindowMode%22%3A%22pretty%22%2C+%22viewWindow%22%3A%7B%22max%22%3Anull%2C+%22min%22%3Anull%7D%2C+%22logScale%22%3Afalse%2C+%22titleTextStyle%22%3A%7B%22color%22%3A%22%23222%22%2C+%22fontSize%22%3A%228%22%2C+%22italic%22%3Atrue%7D%2C+%22textStyle%22%3A%7B%22color%22%3A%22%23222%22%2C+%22fontSize%22%3A%228%22%7D%7D%2C%7B%22useFormatFromData%22%3Atrue%2C+%22viewWindowMode%22%3A%22pretty%22%2C+%22viewWindow%22%3A%7B%22max%22%3Anull%2C+%22min%22%3Anull%7D%2C+%22minValue%22%3Anull%2C+%22maxValue%22%3Anull%2C+%22logScale%22%3Afalse%7D%5D&amp;gco_useFirstColumnAsDomain=true&amp;gco_isStacked=false&amp;gco_booleanRole=certainty&amp;gco_hAxis=%7B%22useFormatFromData%22%3Atrue%2C+%22minValue%22%3Anull%2C+%22maxValue%22%3Anull%2C+%22viewWindow%22%3Anull%2C+%22viewWindowMode%22%3Anull%2C+%22textStyle%22%3A%7B%22color%22%3A%22%23222%22%2C+%22fontSize%22%3A%228%22%7D%7D&amp;gco_legend=right&amp;gco_title=Students+qualifying+for+free+and+reduced+lunch+in+the+Corridor+by+hub%2C+2006+to+2011&amp;gco_legendTextStyle=%7B%22color%22%3A%22%23222%22%2C+%22fontSize%22%3A%2210%22%7D&amp;gco_series=%7B%220%22%3A%7B%22color%22%3A%22%23073763%22%7D%2C+%221%22%3A%7B%22color%22%3A%22%230b5394%22%7D%2C+%222%22%3A%7B%22color%22%3A%22%233d85c6%22%7D%2C+%223%22%3A%7B%22color%22%3A%22%236fa8dc%22%7D%2C+%224%22%3A%7B%22color%22%3A%22%236fa8dc%22%7D%2C+%225%22%3A%7B%22color%22%3A%22%239fc5e8%22%7D%7D&amp;att=true&amp;width=1000&amp;height=685"></iframe>
```

I tried embedding the above code in a simple static HTML page and it worked correctly in Firefox. The next step is to try to replicate Floodlight's rendering process to see why this causes issues in Firefox.

**Comment by ghing** [comment] 2013-09-16 19:25
Here's a jsFiddle that demonstrates the issue outside of the builder: http://jsfiddle.net/geoffhing/V8k5T/

It appears that the problem is with the container element being hidden initially.

**Comment by ghing** [comment] 2013-09-16 20:00
And here's a jsFiddle that shows a possible fix: http://jsfiddle.net/geoffhing/bSPHQ/

When the DOM is ready, the iframe element is removed from the DOM.  When it's container element is shown, the iframe is re-added to the DOM.

This seems like a fairly viable fix, but the question is whether we do this for all iframe elements, or detect certain ones.

I'm assigning this to @patternleaf to look at after he finishes the widget stuff as he's already spent a bit of time looking at embed issues.

**Comment by ghing** [comment] 2013-09-16 20:16
In terms of exposure to this issue, there are 15 published assets that use fusion tables embeds. They appear in these stories:
- Dataviz How-To: Make a bar chart in Fusion Tables
- Federal Issues, Local Problems: SNAP and Denver's Food Security
- The Legacy of 1963: The Reality of Modern Day Segregation
- In the Shadow of the Highway: Schools and Pollution (2/5)

We'd have to look at Google Analytics to see how many times these stories are viewed in Firefox.

This is the Django ORM query I used to find this:

```
from storybase_asset.models import HtmlAsset
assets = HtmlAsset.objects.filter(storybase_asset_htmlassettranslation_related__body__icontains='www.google.com/fusiontables/embedviz', stories__status='published')
assets.count()
```

**Comment by jwirfs-brock** [comment] 2013-10-30 18:13
To add another chapter to the Google embed saga...

I'm not sure if it's a Fusion Tables or  Google Charts embed, but one one in http://dev.floodlightproject.org/en/stories/why-stories-matter-a-reflection-on-the-denver-ca-2/ on section 5/8 is rendering fine in Chrome and Firefox, but not showing up in Safari.

**Comment by mgrayinnovation** [comment] 2015-03-26 18:46
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit

**Closed as completed by mgrayinnovation** 2015-03-26 18:46 UTC
Labels: bug, builder, viewer, 4 points, high
