### ISSUE TITLE
Intermittent blinking/flashing effect while scrolling

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#309] opened 2012-10-10 21:07 UTC
In Firefox 15.0.1, when user scrolls a topic filtered Explore page, the page creates a rapid but intermittent blinking/flashing effect of the sections of the page that are rendering. Both up and down scrolling is affected.

**Comment by wendynorris** [comment] 2012-10-10 21:36
Also occurs in map view on Explore page.

**Comment by patternleaf** [comment] 2012-10-15 14:09
if i understand you correctly, i think this is due to the filter bar going into "sticky" mode which makes the rest of the content jump up, which may change the conditions for the filter bar being sticky or not. with the right geometry, it can jump back and forth. i've added a spacer which keeps the content from jumping around when the bar goes into and out of sticky mode. will assign to you when the changes are available to try to repro.

**Comment by patternleaf** [comment] 2012-10-19 16:16
@tekhneco , if you get a chance could you try to reproduce this on staging and close if you can't? thanks.

**Comment by wendynorris** [comment] 2012-10-19 16:23
Looks good. Issue closed.

**Closed as completed** 2012-10-19 16:33 UTC
Labels: bug, UI/UX, Styling/Cosmetic, launch
