### ISSUE TITLE
Update megamenu to reflect new content organization

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#642] opened 2013-02-21 15:54 UTC
This is a subtask of #426

**Comment by patternleaf** [comment] 2013-02-27 18:43
@ghing @jwirfs-brock @bpawlak would you all mind going to http://deploy.atlas.terrorware.com/ to check in on the megamenu organization? I'm trying to synthesize information in #426 and could use a check-in to see if I'm on the right track. Also I've tweaked a number of style elements to make the implementation a little more sane, but also so that the presentation is more consistent. If you have any recommendations on megamenu styling, let me know. 

(known issue: "Learn how to be a better storyteller" wraps and looks funny on account of how the little hover arrow is implemented.)

**Comment by ghing** [comment] 2013-02-27 18:55
One thing to think about is that on my display, the menu gets weird ("About" gets pushed to a new row) when the window is made narrower (but not unreasonably narrower).  This could be helped by changing the menu items to be shorter (which I think we did originally), e.g. "Skills", "Explore".  The `title` attribute could still be the long version of the titles.

Alternately, we could use media queries to show/hide different versions of the megamenu items that have shorter or longer titles, but I feel like that adds some complexity and is maybe better thought about when we address responsiveness at large.
![Screenshot from 2013-02-27 12:54:22](https://f.cloud.github.com/assets/110420/202329/20e198be-810f-11e2-8713-fded03a86494.png)

**Comment by patternleaf** [comment] 2013-02-27 19:02
@ghing yeah, i actually reduced the margins between the top-level links and addressed a clearing/floating issue that made smaller browser widths even weirder than what you're observing.

our minimum non-responsive width is generally 1000px at this point and it's the My Account menu that is the outlier here. when logged out, the wrapping you see doesn't happen. i'd be interested in maybe changing the way we handle My Account.

**Comment by jwirfs-brock** [comment] 2013-02-27 19:17
@bpawlak Can you share your idea for the megamenus about incorporating the
teasers for each of the second-level pages? You'll be able to describe it
better than I can...

**Comment by bpawlak** [comment] 2013-02-27 22:09
I would actually suggest not bothering to put in the 2nd level nav items in the mega menu and instead using the space to explain what's in those sections.  Same holds true for Storytelling Workshops... don't put the two links, just give an intro/teaser into the section.  Then it'll consistent across the whole site.

**Comment by jwirfs-brock** [comment] 2013-02-27 22:19
@bpawlak @patternleaf @ghing

I just want to make sure we are referring to the same things when we say
2nd level and top level. I'd like to have the second-level nav items listed
in the meganav, if possible (so, for About, that would be The Vision,
Partners, etc.; for News & Updates it would be Storytelling Workshops,
Story-Raisings, etc.). The rest of the space can hold the description of
the top-level pages.

**Comment by patternleaf** [comment] 2013-02-27 22:23
so is it correct that the following: 
- Grow Your Skills
- About

need to be updated to match that format, whereas the rest of the megamenu content is in ok shape?

**Comment by jwirfs-brock** [comment] 2013-02-27 22:28
Well, I was actually thinking something more like this for About, Skills
and News & Updates:

[col 1]
Top Level Title
[col 2]
Second Level Titles
[col 3 and 4]
Top Level Description

That way they all fit the same format.

**Comment by jwirfs-brock** [comment] 2013-02-27 22:30
So for News & Updates that would look like:

[col 1]
News & Updates
[col 2]
Latest Updates
Story-Raisings
Storytelling Workshops
[col 3 and 4]
Like a good story, Floodlight is a work in progress. Here, you’ll find
information about improvements we’re making to the site, storytelling
events we’re holding in the community, storytelling advice, contests, and
more.

**Comment by ghing** [comment] 2013-02-27 22:44
@jwirfs-brock, I don't understand repeating the top level item all by itself in the first column.  Can you clarify what your intention is with that suggestion?

**Comment by bpawlak** [comment] 2013-02-27 22:47
@jwirfs-brock My suggestion was to _not_ show the 2nd level navigation in the meganav only to keep it consistent with the rest of the site sections.

**Comment by jwirfs-brock** [comment] 2013-02-27 22:47
It's just a suggestion -- I'm totally open to better ideas! I've just
noticed that when people interact with the meganav, they tend to forget
that they can just click on the top level menu.

**Comment by jwirfs-brock** [comment] 2013-02-27 22:48
@bpawlak Can you share an outline of what you had in mind? I'm having
trouble seeing how not showing the sub-categories would help people
understand what's in each item.

**Comment by bpawlak** [comment] 2013-02-27 22:54
I think showing the sub-categories are a good idea (it's like a standard drop-down nav menu), I was just trying to say that if you want to be consistent across all of the site sections in the meganav, you could just use text to explain.

**Comment by jwirfs-brock** [comment] 2013-02-27 22:55
@ bpawlak Got it. Do you have a better suggestion for whether we should
also include the top level title? @ghing has a point that it's a bit
awkward floating by itself.

**Comment by jwirfs-brock** [comment] 2013-02-27 23:23
@bpawlak and I just chatted about this over the phone and here's an updated recommendation:

[col 1]
**Top level name**
Second level list
[cols 2, 3,4 -- merged]
Top level description

So, for example, News & Updates will be:

[col 1]
**News & Updates**
Latest Updates
Story-Raisings
Storytelling Workshops
[cols 2, 3, 4]
Like a good story, Floodlight is a work in progress. Here, you’ll find information about improvements we’re making to the site, storytelling events we’re holding in the community, storytelling advice, contests, and more.

**Comment by bpawlak** [comment] 2013-02-27 23:34
Yep, that's what we discussed.

**Comment by patternleaf** [comment] 2013-02-28 15:49
the News & Updates menu has been updated. per discussion on the call this morning, i'm awaiting layout for About and Grow Your Skills from @jwirfs-brock.

by the way, i just switched the non-header links in the megamenu to sans-serif rather than Museo and i think it reads better. other opinions?

**Comment by ghing** [comment] 2013-02-28 15:55
@patternleaf Is this on deploy? I'm not understanding what you mean by "non-header links in the megamenu".  I'm also seeing some layout issues in the "News & Updates" megamenu, but I'll wait to post a screenshot before hearing if this has been updated on deploy.

**Comment by patternleaf** [comment] 2013-02-28 15:59
@ghing it is on deploy. yeah—please post a screenshot; i'm not seeing anything weird.

by "non-header links" i mean this:

![Screenshot 2:28:13 8:59 AM](https://f.cloud.github.com/assets/73439/205990/d957e01e-81bf-11e2-84cf-a772afbe7500.png)

**Comment by ghing** [comment] 2013-02-28 16:04
@patternleaf, even after a hard-refresh/cache clear, I'm neither seeing the font change and getting this weird layout issue:

![Screenshot from 2013-02-28 10:01:48](https://f.cloud.github.com/assets/110420/206000/472966d0-81c0-11e2-942b-9aa7c13da6e0.png)

Maybe an issue with less.js fetching stale CSS?

**Update:** Just tried it in a different browser and I saw the font change and no layout issues.  @patternleaf, can you test this in Chrome just to make sure what I'm seeing is stale CSS and not a Chrome-specific issue?

I'm ok with the different font for sub-menu items.  My only thought is that I'd like it more if the font change were used across menus on the site to differentiate top-level vs. second level pages, but I need to think a little more about the implementation for that.

**Comment by jwirfs-brock** [comment] 2013-02-28 20:59
@patternleaf Here are the meganav outlines for About and Skills:

[col 1]
**About**
The Vision
Community Values
Partners
How it Works [once published]
[cols 2, 3, 4]
[Can we just keep these the way they are? I like how it is now.]

[col 1]
**Skills**
Elements of Storytelling [once published]
Reporting and Information Gathering [once published]
Photos and Images
Data Analysis and Visualization
Video Storytelling [once published]
Audio Storytelling [once published]
Creative Commons [once published]
[cols 2, 3, 4]
Storytelling comes naturally to all of us. But we can always improve with practice. Here, you’ll find online tools and tutorials to help you build your skills.

The first column will have the name of the top-level page, followed by a list of the second-level pages. It probably makes sense to do this in such a way that, when we publish a new page, it updates in the megamenu nav automatically. Is that doable?

**Comment by patternleaf** [comment] 2013-02-28 23:40
@jwirfs-brock OK, those changes are on deploy.

> It probably makes sense to do this in such a way that, when we publish a new page, it updates in the megamenu nav automatically. Is that doable?

it should be, but we should probably make a different issue for that.

ps, what would you all think of a different treatment for menus with text in columns 2-4? not necessarily this but something like this:

![Screenshot-2_28_13-4_32-PM](https://f.cloud.github.com/assets/73439/207852/3b50c9bc-8200-11e2-9d47-2b5549c2e7c5.png)

**Comment by patternleaf** [comment] 2013-02-28 23:41
@ghing not able to reproduce in Chrome for Mac. i have 25.0.1364.99.

**Comment by patternleaf** [comment] 2013-02-28 23:42
@jwirfs-brock note i meant _deploy_ in earlier comment: the changes are on deploy.

**Comment by bpawlak** [comment] 2013-03-01 00:49
I like the design idea, Eric.

**Comment by jwirfs-brock** [comment] 2013-03-01 00:50
@patternleaf I like that treatment!

Ok, I'll open up a separate issue for wiring it into the page content. We
can add that to iteration 12 or 13.

**Comment by ghing** [comment] 2013-03-01 14:46
@patternleaf I like your design treatment of the text in columns 2-4.  Send me a pull request when this is ready and I can take a look at what needs to happen to wire it up so the menu items aren't as hard coded.

**Comment by patternleaf** [comment] 2013-03-01 15:06
@ghing: Just submitted pull #663, which has commits for both this issue and #644.

**Comment by ghing** [comment] 2013-03-01 19:32
STILL TODO:
- Wire in links for news & updates section
- Wire in links programatically

**Comment by patternleaf** [comment] 2013-03-01 22:01
@ghing we'll need the ids for the hard-coded links, correct? looks like the pages on dev don't have them yet. let me know if i should handle this or you. also, can we dupe the data over to deploy at some point?

**Comment by ghing** [comment] 2013-03-01 22:09
@patternleaf, I'm going to open up an issue for the menu wiring and take a stab at that this afternoon and see if I can just pull the subsection links from the dynamic menu structure, avoiding the need to hard-code all the sub-page links.

**Comment by ghing** [comment] 2013-03-01 22:45
@patternleaf, @jwirfs-brock Opened #664 for the wiring up of the menu items dynamically.

**Closed as completed** 2013-03-01 22:55 UTC
Labels: UI/UX, 2 points
