### ISSUE TITLE
Filters not displaying properly

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#375] opened 2012-10-22 20:10 UTC
Win7, Firefox 16.0.1

https://docs.google.com/drawings/d/13thl1Ekli3LinKzxl63bPLMwPsoWVtMbyB0azDKkLyg/edit

Also, just noticed that the "My Account" tab is showing up far right, instead of being right-aligned with right-side of search input box

**Comment by ghing** [comment] 2012-10-23 12:57
This is a duplicate of #358

**Closed as completed by ghing** 2012-10-23 12:57 UTC
Labels: tweak, UI/UX, Styling/Cosmetic
