### ISSUE TITLE
Autosave doesn't seem to be working for a story after it's been published

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#228] opened 2012-09-10 22:36 UTC
When trying to edit a story (after it had been published) in the Story Builder, I found that the auto-save wasn't working. Specifically, I tried to update the Call to Action on [this story](http://staging.denverchildrenscorridor.org/stories/workshop-11-why-do-we-tell-stories/) (by changing 1.1 to a link). Even though the preview indicated the change, when I exited the Story Builder and then returned, the change wasn't saved. 

Maybe we should add a way to do a hard save, because this could get very frustrating to users.

**Comment by jwirfs-brock** [comment] 2012-09-10 22:42
Something else may be going on. After I made the updates, the "last saved" time stamp reflected a time that was later than when the changes were made. But then the updates weren't reflected in the "Explore" page. In fact, the story is no longer loading at all, and I'm not getting this error:

https://docs.google.com/file/d/0B82exFJJWyJqQVBTbEpUanZmRGM/edit

**Comment by ghing** [comment] 2012-09-12 21:53
@jwirfs-brock The issue with the "Page Not Found" error is completely separate and is fixed in #234.  I'll continue to look at the auto-saving issue.

**Comment by ghing** [comment] 2012-09-12 22:04
It looks like the issue isn't with the fact that the story is being published.  I confirmed this by creating a story, publishing it through the builder workflow and then reloading the the builder page.  After reloading the builder I was able to edit the call to action as expected.

Instead, I think the issue is with leaving the builder view for another view.

**Comment by ghing** [comment] 2012-09-12 22:12
This also affects the story information section, but only the summary. A more accurate title for this issue would be "text area auto save doesn't work after leaving and returning to builder view"

**Closed as completed** 2012-09-12 22:29 UTC
Labels: bug, critical, builder
