### ISSUE TITLE
Browsers don't rotate images based on EXIF orientation

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#855] opened 2013-09-05 17:07 UTC
This is a bug reported from Rebecca Arno:

> My picture appears upside down in the published story, even though it looks right side up in all other versions (when i open it here, when I select it for the story).  I have no idea what happened or how to correct it.

Here's the link to her connected story: http://floodlightproject.org/en/stories/whats-the-last-photo-on-your-phone/viewer/#sections/connected-stories ("My Guys")

Note that in the thumbnail it appears right-side-up, but in the story itself it appears upside-down. Weird.

**Comment by jwirfs-brock** [comment] 2013-09-05 17:26
@tekhneco manually fixed the image so that it appears correctly now. We should still try to figure out what caused this problem in the first place, though.

**Comment by jwirfs-brock** [comment] 2013-09-05 17:29
@tekhneco says:

> For the photo problem, I checked the exif meta data and she had either accidentally flipped the photo in an image editor or she took the photo "upside" down on her phone with the shutter button on the left of the handset instead of the right.

**Comment by ghing** [comment] 2013-09-05 17:49
I don't know if this is actually an issue as, based on Wendy's comment the image's data says its supposed to be flipped.

**Comment by jwirfs-brock** [comment] 2013-09-05 17:51
Well, it was showing up in different orientations in different browsers,
and in different orientations in different places on the site (i.e.,
correctly in the builder, not correctly once it was published).

But if you don't think this is something we can address, we can close it.

**Comment by jwirfs-brock** [comment] 2013-09-05 17:52
It could just be a wacky iPhone thing that will just cause more headaches and is an edge case anyway.

**Comment by ghing** [comment] 2013-09-05 17:55
Is there any way you can get me a copy of the original image?

**Comment by wendynorris** [comment] 2013-09-05 18:00
Original image:
![photo_23_](https://f.cloud.github.com/assets/2329239/1090314/ae6938ce-1654-11e3-937b-efd163849885.jpg)

I downloaded the original image and then rotated it left twice to reset it as: 

![photo_23_ll](https://f.cloud.github.com/assets/2329239/1090333/097fce58-1655-11e3-8023-ce14d774d443.jpg)

**Comment by ghing** [comment] 2013-09-05 23:58
It seems like [we're in good company](http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/)

**Comment by ghing** [comment] 2013-09-06 00:19
Ok, so here's what I think the deal is: The photo was taken with the phone upside down, so the actual pixels of the image are really upside down. The iPhone detects this and compensates by setting an orientation (in this case "Rotate 180") in the EXIF data for the image.  When displaying the image, the iPhone applies the EXIF orientation, so it appears right side up.  In my testing, Chrome and Firefox both don't apply the EXIF orientation, so the image appears upside down.  The issue for this in Chrome can be found [here](https://code.google.com/p/chromium/issues/detail?id=56845).

So, when viewing the raw image in the viewer in a browser, the image appears upside down (because this is how the browser does it).  However, the image processing library we use to generate thumbnails **does** handle the EXIF rotation, which is why the image appears right-side-up on the story detail page and in the thumbnail.

So, the problem isn't with our software, it's with the fact that the iPhone and most browsers display the same image differently.

We could address this issue by processing every image uploaded, but I'd recommend that as part of a general strategy for scaling images in the viewer by processing the image rather than using CSS rather than a one-off fix.

**Comment by ghing** [comment] 2013-09-06 00:21
Changed title from "Pictures uploaded from iPhone appearing upside-down in story viewer" to "Browsers don't rotate images based on EXIF orientation"

**Comment by ghing** [comment] 2013-09-06 00:26
@jwirfs-brock My recommendation is that we don't fix this right now since it only affects images that were taken upside down in an environment that automatically shows them right-side-up (like the iPhone).  We're letting the browser show the image as it sees fit, and most don't do the rotation.  If we really want to address this now, we might as well think through a good automated setting for scaling images before showing them in the viewer as this will somewhat decrease page load times when the user uploads a hugely high-res image.  I'm assigning this to you to decide if you want to keep it in Critical Bugs, schedule it for a future iteration, or choose not to try to address it.

**Comment by wendynorris** [comment] 2013-09-06 00:29
Nice sleuthing, Geoff.

Might also help to add a how-to piece for users to avoid this problem by
orienting the phone with the shutter button on bottom (profile) or button
to the right (landscape) since it's a common issue.

**
_wendy norris http://about.me/wendynorris_
 ceo + founder :: tekhne media, inc
a digital information and media collective
720 281 9378 :: mobile

*\* http://about.me/wendynorris
*
*

**Comment by jwirfs-brock** [comment] 2013-09-06 00:32
Yeah, @ghing I'm impressed you got to the root of this problem so quickly. I recommend we not try to fix this issue, since it's something that is such as edge case. I do like @tekhneco's idea about having a how-to piece for orienting the shutter.

Closing.

**Closed as completed** 2013-09-06 00:34 UTC
Labels: bug, viewer

**Comment by wendynorris** [comment] 2013-09-06 00:39
I'm not nearly as artistic as you, Jordan, but I'm happy to take a crack at
a How-To on the "Heartbreak of Photo Rotation."

**
_wendy norris http://about.me/wendynorris_
ceo + founder :: tekhne media, inc
a digital information and media collective
720 281 9378 :: mobile

*\* http://about.me/wendynorris
*
*

On Thu, Sep 5, 2013 at 6:32 PM, Jordan Wirfs-Brock <notifications@github.com

**Comment by jwirfs-brock** [comment] 2013-09-06 00:42
Awesome. And I'll put together a how-to on uploading an image from your
phone to a third-party service for easy embedding (related to issue #857).
