### ISSUE TITLE
Add New Section feedback needs to be changed

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#224] opened 2012-09-07 21:59 UTC
When a user hovers over the space to enter in a new section, we're currently showing that new section immediately to the right of the user's mouse, moving the rest of the sections over.  However, that seems very confusing to people as things are jumping around quite a bit when the user moves the mouse.  

A different suggestion is to simply show a tool-tip like bubble that the user could then click on to insert the new section (see: https://docs.google.com/drawings/d/1PdlRth8WFHitHBjFK1zX9gYsKTsF6f_tjCVDIM6UNGY/edit for reference)

**Comment by ghing** [comment] 2012-09-27 15:44
This is a duplicate of #266.  I'm closing this and moving discussion over there.

**Closed as completed by ghing** 2012-09-27 15:44 UTC
