### ISSUE TITLE
Explore page filters should be mutually exclusive (when you open a new one, previously open one should close)

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#480] opened 2012-11-20 19:09 UTC
From @bpawlak's feeback session with David and Gabriela:
"Filters on Browse should be mutually exclusive.  Right now, I can open all 5 of them at once and making a selection keeps all the rest open, covering up the top of the stories.  Speed associated with selecting/deselecting filters"

Screenshot: https://docs.google.com/file/d/0B82exFJJWyJqeUZXejVwUUlxZjQ/edit

**Comment by patternleaf** [comment] 2013-02-12 22:42
Hm. This is only happening to me inconsistently in FF and Safari. Maybe worse, the little "x" to remove the filter isn't showing up in Safari. Or rather sometimes it's there and other times it's not. Looks like this might deserve a little investigation.

**Comment by patternleaf** [comment] 2013-02-13 17:13
The only time I can repro this specific thing is when a filter drop-down is open as the story list under it is changing. And then I can only get one to be "stuck" open at a time. @bpawlak are you able to reproduce what's in the screenshot? ie, a bunch of filters open at once? if so, could you provide steps?

**Comment by bpawlak** [comment] 2013-02-13 17:36
Ok, I managed to get it to happen again:

![image](https://f.cloud.github.com/assets/2250519/153765/8f8ce8d4-7603-11e2-8c44-f300709e160d.png)

I can't really describe how to reproduce it as I was simply trying different filters (Chrome) and then it happened.

I'm also seeing a bunch of other odd intermittent behaviors:  see below.  I tried to do a search in one of the filter dropdowns and ended up seeing this in the upper left

![image](https://f.cloud.github.com/assets/2250519/153762/6d7fe7f0-7603-11e2-8e3a-bbb5f4b9960d.png)

And the switch between tile, list and map gets cut off and the map is messed up:

![image](https://f.cloud.github.com/assets/2250519/153776/f08e5118-7603-11e2-91ec-4799102e4862.png)

**Comment by bpawlak** [comment] 2013-02-13 17:56
Here's something else I just found:  Two versions of the dropdown appearing at once (one's behind the other)

![image](https://f.cloud.github.com/assets/2250519/153849/9ffeb8d4-7606-11e2-9c1b-4c4ed51cfc4e.png)

**Comment by patternleaf** [comment] 2013-02-13 18:24
yeah, the single drop-down stuck is what i've been able to reproduce and i think both screenshots you've posted are showing that issue. but no luck with the multiple drop-downs stuck as depicted in the original screenshot?

**Comment by bpawlak** [comment] 2013-02-13 18:28
No, I got it to happen again (see the first image in my posting from an hour ago (https://github.com/PitonFoundation/atlas/issues/480#issuecomment-13506529)

**Comment by patternleaf** [comment] 2013-02-13 18:35
sorry: when i said "multiple" i meant "all" as in the original screenshot: (https://docs.google.com/file/d/0B82exFJJWyJqeUZXejVwUUlxZjQ/edit)

that's what i haven't been able to repro and what i was asking about.

to be clear, your screenshot from an hour ago showed two dropdowns showing at once. i have reproduced that and my diagnosis is that under certain conditions a single drop-down gets "stuck" in the visible position. that results in being able to open one (but only one) other drop-down at the same time, including a "new" one attached to the same filter as the stuck one (resulting in the screenshot in https://github.com/PitonFoundation/atlas/issues/480#issuecomment-13507548).

**Comment by bpawlak** [comment] 2013-02-13 18:39
Ok.  I wonder if the issue of a single dropdown getting stuck open is likely related to the issue of multiple dropdowns getting stuck open?  But you're correct, I haven't been able to get multiple dropdowns to stick in the open state.

**Comment by patternleaf** [comment] 2013-02-15 16:37
I've found and fixed the main issue noted here (possible for a drop-down to get stuck open) and made new issues for other bugs discussed:
- #633 
- #631 
- #632

@bpawlak, I'm going to assume that your map rendering issues are related to or will be addressed by #587.

**Comment by bpawlak** [comment] 2013-02-15 17:04
@patternleaf I think #587 is more about the map rendering (which I saw the other day), but if you look at the first picture in that issue, you can see the entire map container is moved up on the page 20 or so pixels so that it cuts off the words (Tile, List, and Map).

It looks like the actual issue is #631, which you just created.

**Comment by patternleaf** [comment] 2013-02-15 17:11
right, i was seeing those as two separate issues:

> And the switch between tile, list and map gets cut off and the map is messed up:
- "the map is messed up" = #587 
- "map gets cut off" = #631

**Closed as completed** 2013-02-18 19:13 UTC
Labels: 2 points
