### ISSUE TITLE
Publish button not working in Firefox after some story edits

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#906] opened 2013-12-02 18:27 UTC
I observed this on dev (but  not production) while testing the updated story workflow (issue #579).

Here is what happened:
- During normal story edits (adding a title, adding new section, adding content to sections), when I navigated to the Publish/Share workflow step, the Publish button worked properly
- When I created a new story and did many complex edits (i.e., reordering sections, editing section titles, changing section layouts), I observed that:
  - When I navigated to the Publish/Share workflow step, the Publish button appeared clickable (i.e., when I moused over it, I got an action tool tip)
  - But when I tried to click the button, nothing happened
  - When I did a refresh, I was then able to successfully use the Publish button

After observing this, I went back and tried it with an existing (yet unpublished) story. Here is what I observed:
- If I just launched the story, but didn't make any edits, I could use the Publish button
- If I launched the story, then reordered sections, the Publish button wasn't working (until I did a refresh)
- If I launched the story, then edited a section title, the Publish button wasn't working (until I did a refresh)

So, here are some of the ways I was able to trigger this (as far as I can tell):
1. Create a new story in Firefox and make lots of complex edits (reorder the sections, change layouts, change section titles, etc.). When I did any one of these in a new story, it seemed to work fine. But when I did a bunch of edits all together, it broke. So I'm not sure what exactly is triggering it.
2. Launch an existing unpublished story and reorder the sections. Then try to publish.
3. Launch an existing unpublished story and edit a section title. Then try to publish.
4. Launch an existing unpublished story and create a new section. Then try to publish.

I also tried launching an existing story and creating a new text asset in an existing section, and the Publish button seemed to work fine. Weird.

**Comment by ghing** [comment] 2013-12-03 14:16
I suspect that the issue isn't actually with editing any particular content (reordering section, changing section title, etc.) but with switching between workflow steps, which then re-renders the view for the publish button, `PublishButtonView`.  I was able to replicate the issue like this:
1. Load an existing story in the builder.
2. Click on the Publish/Share tab
3. Click on the Build tab
4. Click on the Publish/Share tab
5. Press the "Publish My Story" button

Expected behavior: Story is published

Observed behavior: Nothing

**Comment by ghing** [comment] 2013-12-03 14:18
The quick fix is to just call `this.delegateEvents()` in `PublishButtonView.render()`, but I'm going to see if we can avoid re-rendering altogether.

**Comment by ghing** [comment] 2013-12-03 14:35
@jwirfs-brock, I believe this is now fixed.  Assigning to you to confirm.

**Comment by mgrayinnovation** [comment] 2015-04-05 02:56
Quite a bit of work done here ... worth testing when we get to our launch phase ...

**Closed as completed** 2016-06-28 19:52 UTC
Labels: bug, builder, UI/UX
