### ISSUE TITLE
Add data section needs progress indicator when uploading files

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#732] opened 2013-04-30 00:29 UTC
From sandbox test story on dev.floodlight: 
http://dev.floodlightproject.org/stories/375044e162aa40968ff239a6d52b2aec

There is no indicator marking upload progress when adding data. I mistakenly uploaded 5 copies of the same data set because I couldn't tell the site was processing the first request. 

Then, I couldn't delete the unwanted copies. Delete button did not respond. 

Forced to delete all data and start over. 

Update: This is being tested in the development instance with version 63afe9dd9784c0b233e4b1e0656f7e7cf7670e64

**Comment by ghing** [comment] 2013-04-30 18:54
TODO:
- Check if there's actually no upload progress, or if its masked because the upload happens so fast.
- Further test delete button behavior.  It worked for me, but in one case it seemed like I had to click it twice.

**Comment by ghing** [comment] 2013-05-09 21:57
There isn't an upload progress handler implemented, so the lack of an upload progress handler is a result of it not being implemented, not a bug where it's not being displayed.

I did some further testing in both Firefox and Chrome and couldn't replicate the issue with the delete button

**Comment by ghing** [comment] 2013-05-13 17:09
Moving this to Iteration 14. We should consider having better looking progress indicators for both asset uploads and for dataset uploads.  I'm giving this the low label because it might not be relevant to how we do data set uploads in implementing #583.

**Closed as completed** 2013-06-18 12:44 UTC
Labels: low, builder, UI/UX
