### ISSUE TITLE
Chart thumbnail does not display in Build page

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#735] opened 2013-04-30 00:42 UTC
From sandbox test story on dev.floodlight:
http://dev.floodlightproject.org/stories/375044e162aa40968ff239a6d52b2aec

After adding a chart to the side-by-side layout in the build section, there is no thumbnail to represent the addition of the chart. The chart title, source and caption do appear on the build page. 

The chart appears as expected in the published story. 

Firebug console errors: 

> Timestamp: 4/29/13 6:05:47 PM
> Error: SyntaxError: missing ) in parenthetical
> Source File: http://ajax.googleapis.com/ajax/static/modules/gviz/1.0/chart.js?_=1367280346874
> Line: 7, Column: 60
> Source Code:
> art({pushState: true, root: storybase.builder.APP_ROOT}); });)
> 
> Timestamp: 4/29/13 6:06:26 PM
> Error: The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
> Source File: http://www.illumination-for-developers.com/firebuganalytics/
> Line: 0
> 
> Timestamp: 4/29/13 6:06:33 PM
> Error: TypeError: window._content is null
> Source File: chrome://pixelperfect/content/utils.js
> Line: 62
> 
> Timestamp: 4/29/13 6:10:03 PM
> Error: TypeError: this.onlyUserStylesCheckbox is null
> Source File: resource://gre/modules/devtools/CssHtmlTree.jsm
> Line: 691

**Comment by ghing** [comment] 2013-04-30 21:27
I think this is a duplicate of #187.  I added the embed code over in that issue.  I'm going to close this one.

**Closed as completed** 2013-04-30 23:15 UTC
Labels: bug, builder
